name             'rubycas'
maintainer       'Squaremouth'
maintainer_email 'devops@squaremouth.com'
license          'MIT'
description      'Installs/Configures RubyCAS'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.7.0'

depends 'database'
depends 'god'
depends 'mysql', '<= 4.1.2'
depends 'mysql-chef_gem'
depends 'nginx'
depends 'postgresql'
depends 'rvm'
depends 'logrotate'
