name             'rubycas'
maintainer       'Squaremouth'
maintainer_email 'cstephan@squaremouth.com'
license          'All rights reserved'
description      'Installs/Configures RubyCAS'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.5.0'

depends 'database'
depends 'god'
depends 'mysql'
depends 'nginx'
depends 'postgresql'
depends 'rvm'
depends 'logrotate'
